name: Test Workflow

on: [pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get Changed Files
        id: changed
        uses: foodee/gh-action-get-changed-files@feature/test2
        with:
          paths: ^asdf.js ^main.js

      - name: Echo Match
        if: steps.changed.outputs.matched == 'true'
        run: echo Matched
